#!/usr/bin/env python
import findrox; findrox.version(2,0,0)
import rox, os, sys

__builtins__._ = rox.i18n.translation(os.path.join(rox.app_dir, 'Messages'))


import rmenu
if len(sys.argv) > 1:
	main = rmenu.RoxMenu(sys.argv[1])
else:
	main = rmenu.RoxMenu(1)

main.show_all()
rox.mainloop()
