#!/usr/bin/env python

import findrox; findrox.version(1, 9, 13)
import rox, os, sys

__builtins__._ = rox.i18n.translation(os.path.join(rox.app_dir, 'Messages'))

import rmenu

if sys.argv[0].endswith('AppRun'):
    rox.croak(_("Menu is meant to be used as a ROX panel applet only.\n\n"
      "Drag it to your panel to run it!"))
elif sys.argv[0].endswith('AppletRun'):
    try:
        main = rmenu.RoxMenu(long(sys.argv[1]))
    except (IndexError, ValueError):
        rox.croak(_("Run as an applet but got no valid file descriptor.\n\n"
          "This should not happen."))
    except:
        rox.report_exception()

main.show_all()
rox.mainloop()
